### ISSUE TITLE
Chef should check the character count of a message before reporting a successful save

### ISSUE THREAD

**Issue by Reinms** [xiaoxiao921/CHEF#3]
Currently if you make a custom message that is close to the 2000 character limit (Close enough that there isn't room for chef to prepend the owner and recipe info) chef will still report a successful save but will not be able to send the message on command. It should have some kind of error for this case as it is very unclear.

**Comment by xiaoxiao921** [comment]
Thanks for the detailed report, fixed in 9931ad0
